Repository lacework/go-sdk, pull requests merged in 2020-05, with the labels that each got.

#87 feat: Add lacework-cli containers
  Dockerfile
  Makefile
  cli/images/amazonlinux-2/Dockerfile
  cli/images/centos-8/Dockerfile
  cli/images/debian-10/Dockerfile
  cli/images/ubi-8/Dockerfile
  cli/images/ubuntu-1804/Dockerfile
  cli/images/windows-nanoserver/Dockerfile
  scripts/release_containers.sh
Labels: feat

#91 feat(cli): new 'integration show' cmd
  api/integrations_aws.go
  api/integrations_azure.go
  api/integrations_cont_reg.go
  api/integrations_gcp.go
  cli/cmd/event.go
  cli/cmd/integration.go
  go.mod
  go.sum
  scripts/release_containers.sh
  vendor/github.com/mitchellh/mapstructure/.travis.yml
  vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/modules.txt
Labels: feat

#92 fix(api): parsing event details 'cpu_percentage'
  api/events.go
  api/events_test.go
  scripts/release_containers.sh
Labels: bug

#96 feat(cli): add aliases to integration and event cmds
  cli/cmd/event.go
  cli/cmd/integration.go
Labels: feat

#95 feat(cli): preconfigure using key file from the WebUI
  cli/README.md
  cli/cmd/configure.go
Labels: feat

#100 fix(api): use correct types on events response
  api/events.go
Labels: bug

#104 feat: incident analysis, visualize event details
  api/events.go
  cli/cmd/event.go
  cli/cmd/outputs.go
  internal/array/join.go
Labels: feat

#106 feat: manage compliance reports for GCP, Azure, and AWS
  api/api.go
  api/client.go
  api/compliance.go
  api/compliance_aws.go
  api/compliance_azure.go
  api/compliance_gcp.go
  cli/cmd/compliance.go
  cli/cmd/compliance_aws.go
  cli/cmd/compliance_azure.go
  cli/cmd/compliance_gcp.go
  cli/cmd/configure.go
  cli/cmd/integration.go
  integration/compliance_test.go
  integration/framework_test.go
  integration/help_test.go
  integration/integration_test.go
Labels: feat

#110 ci: fix typo in release.sh script
  scripts/release.sh
Labels: bug

#115 feat(cli): avoid displaying API key secret
  cli/cmd/configure.go
  cli/cmd/prompt.go
  cli/cmd/prompt_test.go
  integration/configure_test.go
Labels: feat

#116 Release v0.1.13
  CHANGELOG.md
  RELEASE_NOTES.md
  VERSION
  scripts/release.sh
Labels: release

#119 fix(spelling) Fixes event header misspelling
  cli/cmd/event.go
Labels: bug

#121 feat: auto-populate account with --profile flag
  cli/cmd/configure.go
  integration/configure_test.go
Labels: feat

#124 feat: understand vuln reports with 0 vulnerabilities
  api/vulnerabilities.go
  cli/cmd/vulnerability.go
Labels: feat
