Repository lacework/go-sdk, pull requests merged in 2021-04, with the labels that each got.

#360 fix(api): update time format in API response
  api/vulnerabilities_container.go
  api/vulnerabilities_container_test.go
Labels: bug

#357 ci: switch over our CI to CodeFresh
  .circleci/config.yml
  .github/dependabot.yml
Labels: ci

#359 fix(cli): mask ServiceNow integration password
  cli/cmd/integration_service_now_channel.go
Labels: bug

#367 Release v0.4.0
  CHANGELOG.md
  RELEASE_NOTES.md
  VERSION
  api/version.go
  cli/docs/lacework_compliance_aws_get-report.md
  cli/docs/lacework_compliance_azure_get-report.md
  cli/docs/lacework_compliance_google_get-report.md
  cli/docs/lacework_integration_list.md
  cli/docs/lacework_integration_show.md
  cli/docs/lacework_vulnerability_container_scan-status.md
  cli/docs/lacework_vulnerability_container_scan.md
  cli/docs/lacework_vulnerability_container_show-assessment.md
  cli/docs/lacework_vulnerability_host_scan-pkg-manifest.md
  cli/docs/lacework_vulnerability_host_show-assessment.md
Labels: release

#368 test(integration): fix failing test from API changes
  integration/host_vulnerability_test.go
Labels: chore

#369 refactor(cli): use official url for agent installs
  cli/cmd/agent_install.go
  cli/cmd/agent_install_test.go
Labels: cli

#376 fix(cli): match err message changed in server resp
  cli/cmd/vuln_container.go
Labels: bug, cli

#377 feat(cli): split list of Google project id and alias
  cli/cmd/compliance_gcp.go
  cli/cmd/compliance_gcp_test.go
Labels: cli, feat

#380 fix(cli): split GCP projects with parentheses
  cli/cmd/compliance_gcp.go
  integration/compliance_gcp_test.go
Labels: bug

#378 chore: run goimports-reviser to order imports
  api/events_test.go
  api/http_test.go
  api/integration_alert_channels_test.go
  api/integrations_ctr_reg_ecr_access_key_test.go
  api/integrations_ctr_reg_ecr_cross_account_test.go
  api/integrations_ctr_reg_test.go
  api/logging.go
  api/vulnerabilities_container.go
  cli/cmd/access_token.go
  cli/cmd/compliance_gcp_test.go
  cli/cmd/compliance_test.go
  cli/cmd/vuln_html.go
  integration/host_vulnerability_test.go
  integration/version_test.go
Labels: chore

#379 fix(cli): Json result adheres to filters for cmd get-report (aws,gcp,azure)
  cli/cmd/compliance.go
  cli/cmd/compliance_aws.go
  cli/cmd/compliance_azure.go
  cli/cmd/compliance_gcp.go
  integration/compliance_aws_test.go
  integration/event_test.go
Labels: bug

#384 fix(cli): get compliance reports from AWS accounts w/aliases
  cli/cmd/compliance_aws.go
  cli/cmd/compliance_azure.go
  cli/cmd/compliance_azure_test.go
  cli/cmd/compliance_gcp.go
  cli/cmd/compliance_gcp_test.go
  integration/compliance_aws_test.go
  integration/compliance_azure_test.go
  integration/compliance_gcp_test.go
Labels: bug

#386 Release v0.5.0
  CHANGELOG.md
  RELEASE_NOTES.md
  VERSION
  api/version.go
  cli/docs/lacework_vulnerability_host_list-cves.md
  cli/docs/lacework_vulnerability_host_show-assessment.md
Labels: release
